
title: Sobre mim
url: 'http://junlulocky.com'
baseurl: 'Luis Terra' #change it according to your repository name



# Profile information
yourname: Luis Fl치vio Terra  ## put your name
title: 'Graduando em Engenharia Mec칙nica Aeron치utica, Desenvolvedor Front-End'  ## your title
location: Itajub치, MG


## Social Profiles
facebook: https://www.facebook.com/luisflavio.costa  ## your facebook account url
twitter: http://www.twitter.com  ## your twitter account url
linkedin: https://www.linkedin.com/in/luis-fl%C3%A1vio-terra/  ## your linkedin account url
dribbble: http://www.dribble.com  ## you dribbble account url
foursquare: http://www.foursquare.com  ## your foursquare account url
github: https://github.com/lflaviocosta
google+: https://plus.google.com/u/0/113087114482182084559




# Update all the sections by editing the files inside _includes folder.
